### ISSUE TITLE
Is it possible to disable swiping with listview?

### ISSUE THREAD

**Issue by awaik** [bxqm/sliding_sheet#100]
### Description

If we create `SlidingSheet` with `customBuilder: buildInfiniteChild,` https://github.com/bxqm/sliding_sheet/blob/3801bd57887fe74d1f451c2679d5ec3bd49299e1/example/lib/main.dart#L261
the sliding sheet will scrolling with this listview (look attached gif).

### Expected behaviour

Is it possible to disable sliding sheet scrolling with listview?

https://user-images.githubusercontent.com/5330807/139848406-4a1abc4b-beb9-42c4-8593-3bbdfef484dd.mp4

**Comment by bxqm** [comment]
You can put a ListView inside the normal builder. You don't need the customBuilder for that, if I understand your problem correctly.

**Comment by awaik** [comment]
You saved my day, thank you!
