### ISSUE TITLE
If slidingBottomSheet is Full Screen I want it to have scroll with body in its header. How can I do that?

### ISSUE THREAD

**Issue by FatihAydin52** [bxqm/sliding_sheet#98]
If slidingBottomSheet is Full Screen I want it to have scroll with body in its header. How can I do that? Currently the header stays fixed when full screen. Only the body area can be scrolled.

**Comment by bxqm** [comment]
I'm not sure what you are trying to achieve. If you want the header area to be scrollable, you have to put the header area in a `SingleChildScrollView`, if you want the header to be scrollable with the body, you have to put the header simply in the body.
